version: "3.9"
services:
  php:
    container_name: php72
    build:
      context: ./container/php
      dockerfile: Dockerfile
    volumes:
      - app_path:/var/www/app
    entrypoint: "${ENTRYPOINT_PATH}"

volumes:
  app_path:
    driver: local
    driver_opts:
      type: none
      device: ${APP_PATH}
      o: bind